### ISSUE TITLE
Add support for http-ilp

### ISSUE THREAD

**Issue by michielbdejong** [sharafian/web-monetization-video-stream#2]
"Under the video, the page will tell you that your extension is disabled, and give a receiver URL to pay to manually. Copy the URL down."

There's a protocol for that! ;)

Especially now that http-ilp will support both the `interledger-psk2` and `interledger-streams` payment method identifiers (you mentioned this, but where is the latter documented?), it seems like overlap if both web-monetization and http-ilp cover the use case shown in this demo?

**Comment by michielbdejong** [comment]
I guess in this case, where the video actually stops if you don't pay, the use case falls somewhere inbetween the sweet spot of web-monetization (browser sends automatic donations to sites which the user visits) and that of http-ilp (http calls for which payment is required).

A clear advantage of web-monetization is that it can be implemented in a browser extension, and doesn't require a change in the browser software itself.

A clear advantage of http-ilp is that it can be implemented on any http-accessible resource (not just a html+js web page) and doesn't require the client to parse and run any javascript.

Our third option, web payments, doesn't feel like a good fit here, because it would be too much work to do a web payments flow for every few seconds of video; that's more useful for larger purchases.

**Comment by sharafian** [comment]
I've mostly just got the receiver URL in there for demo purposes, so I can conveniently show the video buffering and then playing and then buffering. I wouldn't put that in a final version of this

**Comment by michielbdejong** [comment]
I agree the current cut-and-paste URL is not a serious option. But do you agree that then http-ilp with the `interledger-streams` payment method would be a good solution? (still don't know where it's documented, sorry, just know you said it's similar to https://github.com/interledger/rfcs/pull/319/files)

**Comment by sharafian** [comment]
If the browser supported it then that may make sense. We would also have to specify that `interledger-streams` may return the content concurrently with the payment. Right now the way it's implemented is that it streams money and then stops once it gets data back.

**Comment by michielbdejong** [comment]
The point I was trying to make is that we have way too many ways to set up a payment; if we want to be the standardization of how people set up payments (regardless of how they actually execute the payment, i.e. Interledger or otherwise), we should shorten the following list:
1. spsp
1. spsp + WebFinger (deprecated, but still used by ilp-kit)
1. spsp + payment pointer
1. spsp + web payment
1. http-ilp + psk1 (still used in the tutorials)
1. http-ilp + psk2
1. http-ilp + streams (proposed verbally, but not implemented or documented yet?)
1. web-monetization

Sure, each of them serves a slightly different UX, but asking people to implement seven different payment setup flows is just too many.

**Comment by sharafian** [comment]
A lot of these items are just small wrappers over the transport protocol, though. SPSP itself is about 50 lines, including payment pointers. SPSP + Webfinger can be removed, but even if we wanted to keep supporting it it would be <10 loc.

I definitely agree that we should pare down the transport level until we have one pretty standard option, because implementing transport protocols is challenging. But I don't think we need to remove application-level APIs as aggressively.

**Comment by michielbdejong** [comment]
OK, well this is just a demo so it's fine if you leave it as it is.
